export enum ActionType {
    ADD_APP = 'ADD_APP',
    DEL_APP = 'DEL_APP',
    FOCUS_APP = 'FOCUS_APP',
    MINIMIZE_APP = 'MINIMIZE_APP',
    TOGGLE_MAXIMIZE_APP = 'TOGGLE_MAXIMIZE_APP',
    FOCUS_ICON = 'FOCUS_ICON',
    SELECT_ICONS = 'SELECT_ICONS',
    FOCUS_DESKTOP = 'FOCUS_DESKTOP',
    START_SELECT = 'START_SELECT',
    END_SELECT = 'END_SELECT',
    POWER_OFF = 'POWER_OFF',
    CANCEL_POWER_OFF = 'CANCEL_POWER_OFF',
};
